// <auto-generated />
namespace TutorialMVC70486.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CAMBIOS02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CAMBIOS02));
        
        string IMigrationMetadata.Id
        {
            get { return "201605121047169_CAMBIOS02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
